public with sharing class UniversalTimeConversion {
    public UniversalTimeConversion() {

    }
    public static void getNowTimeForGivenTz(String inputTz){
 
    } 
    public static void getThisTimeInGivenTz(Datetime inputDt, String inputTz){
 
    }
    public static void getTodayDateGivenTz(String inputTz){
 
    }
    public static void getTodayDayForGivenTz(String inputTz){
 
    }
    public static void iAmXHoursAheadOfGivenTz(String inputTz){
 
    }
    public static void iAmXMinutesAheadOfGivenTz(String inputTz){
 
    }
    public static void iAmXSecondsAheadOfGivenTz(String inputTz){
 
    }
    public static void getOffsetForGivenTz(String inputTz){
 
    }
    public static void getMyOffsetDiffForGivenTz(String inputTz){
 
    }
}